### PR TITLE
Changeset fix network deps

### PR DESCRIPTION
**Pull request by bogdanm**
Do not merge yet.

### CODE REVIEW

**Comment by miklis** [comment]
Build finished. No test results found.

**Comment by bogdanm** [comment]
**Changeset**: update dependencies of network related modules

**Changes in set**:

- ARMmbed/sal-iface-eth/pull/8
- ARMmbed/sal-driver-lwip-k64f-eth/pull/6
- ARMmbed/sal-stack-lwip/pull/24
- ARMmbed/sal/pull/22
- **ARMmbed/sockets/pull/30** (this change)

**Top level change**: this change

**Comment by bogdanm** [comment]
**NOTES**

- I went the usual way of creating a new minor when updating minors of dependencies, to minimize chances of breaks. I might have gotten away with keeping the previous minor on some modules, but I felt it's safer to be consistent and create new minors in all modules.
- Unlike other PRs, the ones in this changeset also contain the new proposed version of the module (in this case, the new minors). It's mostly an experiment, let's see if adding this information in PRs is worth doing.

Tested by linking locally and compiling each change in turn with `frdm-k64f-gcc`. A separate PR for `mbed-example-network` will follow.

**Comment by bogdanm** [comment]
Ready to merge, but **please only merge the whole changeset**. @bremoran @0xc0170

**Comment by bremoran** [comment]
+1

**Comment by bogdanm** [comment]
@bremoran: please publish version 0.6.0, I'm not a module owner.

**Pull request merged**
